### ISSUE TITLE
ERROR in Testing the Tutorial Overlay

### ISSUE THREAD

**Issue by Yongbozzz** [drichmond/RISC-V-On-PYNQ#14]
Hi,in the fourth notebook:Packaging an Overlay .Got an issue
Full Output
![3ZP31~5~VRFSN7_L_W$IKR1](https://user-images.githubusercontent.com/53030444/61992722-681ead00-b094-11e9-8684-edc0c561c70e.png)
(PS:I skip the second notebook and use the .bit、.tcl files you provided)
maybe you can't see the picture ,i copy the error imformation just in case
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-6a9ce8bd6990> in <module>()
      3 sys.path.insert(0, '/home/xilinx/RISC-V-On-PYNQ/riscvonpynq/picorv32/')
      4 
----> 5 import tut.tutorial
      6 #import TutorialOverlay
      7 overlay = TutorialOverlay("/home/xilinx/RISC-V-On-PYNQ/riscvonpynq/picorv32/tutorial.bit")

/home/xilinx/RISC-V-On-PYNQ/riscvonpynq/picorv32/tut/tutorial.py in <module>()
     21     pass
     22 
---> 23 class TutorialProcessor(BramProcessor):
     24     """Hierarchy driver for the PicoRV32 BRAM Processor
     25 

NameError: name 'BramProcessor' is not defined
---------------------------------------------------------------------------
I am trying to solve it but failed(comes some other errors or warning)
Could you give me some advice ,ThankU

**Comment by Deepakpy** [comment]
Hello, I am facing the same issue can you tell me how you resolved it.

**Comment by Yongbozzz** [comment]
https://blog.csdn.net/qq_39229006/article/details/98598315

**Comment by Deepakpy** [comment]
I was able to fix the import paths post-import of the processor facing below issue:
https://github.com/drichmond/RISC-V-On-PYNQ/issues/20

**Comment by Deepakpy** [comment]
from riscvonpynq.Processor import BramProcessor which solved the above issue. However the %%riscv test overlay still says could not find IP
