### ISSUE TITLE
Issues regarding naming

### ISSUE THREAD

**Issue by codspalaniappan95** [drichmond/RISC-V-On-PYNQ#2]
In the notebook 'Creating a RISC-V Processor Bitstream' , for the part 'skipping steps in the notebook' - in order to skip the second step the following are asked to be done, 'copy picorv32.tcl and picorv32.bit from <Path-To-RISC-V-On-PYNQ>/riscvonpynq/picorv32/tutorial/gold/ to <Path-To-RISC-V-On-PYNQ>/riscvonpynq/picorv32/tutorial/.

1. The folder is named as 'tut' and not 'tutorial'
2. The files picorv32.tcl and picorv32.bit are not present. Only tutorial.tcl and tutorial.bit are present.

**Comment by drichmond** [comment]
Can you make a pull request?
